### ISSUE TITLE
Upcloudilta palvelimet

### ISSUE THREAD

**Issue by woltage** [qlma/meta#1]
https://twitter.com/JoelPihlajamaa/status/624129413932843008

**Comment by woltage** [comment]
Käyttäjätunnus luotu ja odottaa Upcloudilta krediittejä.

**Comment by d2s** [comment]
Hyvä että projekti etenee. :+1:

**Comment by woltage** [comment]
No joo, kyl töitä riittää silti :)

**Comment by woltage** [comment]
Krediitit saatu ja tunnukset löytyy.
