### ISSUE TITLE
Qlma.fi verkkosivut

### ISSUE THREAD

**Issue by woltage** [qlma/meta#3]
Kommentit: https://trello.com/c/kw2g8N24

**Comment by miro** [comment]
^ tuo Trello on yksityinen, tarkoituksella vai vahingossa?

**Comment by woltage** [comment]
@miro: Otettiin toi Trello pois käytöstä ja kaikki on Githubissa vain nykyään.

**Comment by woltage** [comment]
Pitää kyllä harkita tuota Trelloa vielä, ei tämä Meta projekti niin kätevä ole, mitä ensiksi ajattelin.
